spring:
  application:
    name: class-builder

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: cb-admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate.jdbc.time_zone: Europe/Kyiv
    hibernate:
      ddl-auto: create-only
